"""Migracion Borrar migracion anterior

Revision ID: 83b9ec2b26a1
Revises: 57286e62b45b
Create Date: 2020-04-08 12:59:01.617559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83b9ec2b26a1'
down_revision = '57286e62b45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'asdas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('asdas', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
